name: traco
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - aiohttp
  - aiosignal
  - anyio
  - argon2-cffi
  - asttokens
  - attrs
  - babel
  - beautifulsoup4
  - bleach
  - brotli
  - brotli-python
  - cffi
  - charset-normalizer
  - comm
  - contourpy
  - cryptography
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - exceptiongroup
  - executing
  - filelock
  - fonttools
  - fqdn
  - frozenlist
  - fsspec
  - gmpy2
  - google-auth
  - google-colab
  - h11
  - h2
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_pygments_lexers
  - isoduration
  - jedi
  - jinja2
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - kiwisolver
  - lcms2
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyrsistent
  - python-dateutil
  - pytz
  - pyyaml
  - requests
  - setuptools
  - six
  - sniffio
  - soupsieve
  - terminado
  - tornado
  - traitlets
  - typing-extensions
  - tzdata
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - widgetsnbextension
  - zipp
